### ISSUE TITLE
Schematic: bts4140

### ISSUE THREAD

**Issue by jsb1** [OpenSource-EBike-firmware/TSDZ2_wireless#3]
Hey, cool what You are doing there!

Just a little hint: 
The bts4140 cannot be controlled directly from MCU. You must put a small high-voltage Mostfet (BSS100?) in between and reverse the Logic. 
How much current has to be switched by the bts4140? Maybe a simple pnp and two Resistors would be a simple replacement.

With best Regards,
 Jörg

**Comment by casainho** [comment]
Thanks. Yes, I just found that when I tested. I used a small MOSFET like BSS100 and it worked. The schematic will be updated.
